const students = [
  { name: "Aaditya Rajbanshi", photo: "1.jpg" },
  { name: "Aashish Hasda", photo: "2.jpg" },
  { name: "Alisha Dawadi", photo: "3.jpg" },
  { name: "Anish Shrestha", photo: "4.jpg" },
  { name: "Ankita Baral", photo: "5.jpg" },
  { name: "Anu Rajbanshi", photo: "6.jpg" },
  { name: "Arjun Dhungel", photo: "7.jpg" },
  { name: "Ashim Lamsal", photo: "8.jpg" },
  { name: "Asmin Acharya", photo: "9.jpg" },
  { name: "Av Rajbanshi", photo: "10.jpg" },
  { name: "Avinash Shah", photo: "11.jpg" },
  { name: "Aviyan Budhathoki", photo: "12.jpg" },
  { name: "Basanta Adhikari", photo: "13.jpg" },
  { name: "BIMAL GHORSAI", photo: "14.jpg" },
  { name: "BINAYAK KATTEL", photo: "15.jpg" },
  { name: "Bishop Poudel", photo: "16.jpg" },
  { name: "Deepika Acharya", photo: "17.jpg" },
  { name: "Devendra Raj Gautam", photo: "18.jpg" },
  { name: "Dipesh Timsina", photo: "19.jpg" },
  { name: "Dipswari Acharya", photo: "20.jpg" },
  { name: "Gayatra Baskota", photo: "21.jpg" },
  { name: "Joshna Khadka", photo: "22.jpg" },
  { name: "Kailash Prasai", photo: "23.jpg" },
  { name: "Karan Rajbanshi", photo: "24.jpg" },
  { name: "Karuna Kumari Rajbanshi", photo: "25.jpg" },
  { name: "Madhav Bhattarai", photo: "26.jpg" },
  { name: "Manish Ghimire", photo: "27.jpg" },
  { name: "Neharika Neupane", photo: "28.jpg" },
  { name: "Nemika Thapa", photo: "29.jpg" },
  { name: "Nimisha Rimal", photo: "30.jpg" },
  { name: "Nirdesh Chauhan", photo: "31.jpg" },
  { name: "Nirjala Gahatraj", photo: "32.jpg" },
  { name: "Nishal Niraula", photo: "33.jpg" },
  { name: "Nishma Khatiwada", photo: "34.jpg" },
  { name: "Noel Pradhan", photo: "35.jpg" },
  { name: "Oseen Niroula", photo: "36.jpg" },
  { name: "Pragyan Gautam", photo: "38.jpg" },
  { name: "Prajit Bhattarai", photo: "39.jpg" },
  { name: "Prakhyati Budhathoki", photo: "40.jpg" },
  { name: "Prakriti Paudel", photo: "41.jpg" },
  { name: "Pranisha Shrestha", photo: "42.jpg" },
  { name: "Pranjal Khanal", photo: "43.jpg" },
  { name: "Raju Neupane Khatri", photo: "45.jpg" },
  { name: "Raymon Chapagai", photo: "46.jpg" },
  { name: "Rikesh Giri", photo: "47.jpg" },
  { name: "Roshan Newar", photo: "49.jpg" },
  { name: "SADHANA DAHAL", photo: "50.jpg" },
  { name: "Sagona Gautam", photo: "51.jpg" },
  { name: "Sajina Banjara", photo: "52.jpg" },
  { name: "Samarpan Rai", photo: "53.jpg" },
  { name: "Sanju Shah", photo: "54.jpg" },
  { name: "Sarika Khatiwada", photo: "55.jpg" },
  { name: "Sarika Rai", photo: "56.jpg" },
  { name: "Saujan Khanal", photo: "57.jpg" },
  { name: "Saurav Mishra", photo: "58.jpg" },
  { name: "SONY SARU", photo: "59.jpg" },
  { name: "Sulabh Dahal", photo: "61.jpg" },
  { name: "Susmita Bista", photo: "62.jpg" },
  { name: "Suvam Bista", photo: "63.jpg" },
  { name: "Tekendra Rai", photo: "64.jpg" },
  { name: "Urmila Acharya", photo: "65.jpg" },
  { name: "Yuddha Bikram Sapkota", photo: "66.jpg" },
  { name: "Aditya Dhungana", photo: "68.jpg" },
  { name: "Rohan Shah", photo: "69.jpg" },
  { name: "Kabin Bhetwal", photo: "70.jpg" },
];

export default students;
